[cosmic-ray]
module-path = "src"
timeout = 30.0
test-command = "python -m pytest test"
excluded-modules = [
    "src/untestable_class.py",
]

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.filters.operators-filter]
exclude-operators = [
    "core/RemoveDecorator",
]

